spring:
  datasource:
    url: jdbc:mysql://upstyle-db.cjwwi4eyogmp.ap-northeast-2.rds.amazonaws.com:3306/upstyle
    username: admin
    password: upstyle2025!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-authentication-method: client_secret_post
            client-id: 698248660337qiq5orai985jarf8gbgr0tl13hk1b0sb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
